import { ShieldAlert } from "lucide-react";

import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CitationList } from "@/features/research/CitationList";
import { EvidencePanel } from "@/features/research/EvidencePanel";
import { asSynthesisOutput } from "@/types/research-meta";
import { asCitation } from "@/types/citation";
import type { components } from "@/types/api";

type ResearchRunDetail = components["schemas"]["ResearchRunDetail"];

/** Phase 18/19/22/25/26/27: renders exactly what the backend decided —
 * `grounding_status` is never recomputed or reinterpreted here, and an
 * `insufficient_evidence` result is shown as a safety feature, not an
 * error. No fallback answer is ever generated client-side. */
export function ResearchResult({ run }: { run: ResearchRunDetail }) {
  const citations = (run.citations ?? []).map(asCitation);
  const synthesisStep = run.steps?.find((step) => step.node_name === "synthesis");
  const synthesis = asSynthesisOutput(synthesisStep?.output_payload ?? null);

  if (run.grounding_status === "insufficient_evidence") {
    return (
      <Card className="border-warning/40 bg-warning/5">
        <CardHeader>
          <div className="flex items-center gap-2">
            <ShieldAlert className="h-5 w-5 text-warning" />
            <CardTitle className="text-base">Insufficient Evidence</CardTitle>
          </div>
        </CardHeader>
        <CardContent className="flex flex-col gap-3">
          <p className="text-sm text-foreground">
            The available knowledge base did not contain enough relevant evidence to
            answer this question. AIKDAP does not generate an answer when it cannot
            ground one in your documents.
          </p>
          <div className="flex gap-6 text-sm text-muted-foreground">
            <span>Evidence found: {citations.length}</span>
            <span>Providers used: {synthesis?.provider ?? "None"}</span>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <CardTitle className="text-base">Research Result</CardTitle>
            {run.grounding_status && (
              <StatusBadge domain="grounding" value={run.grounding_status} />
            )}
          </div>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          {run.final_answer ? (
            <p className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">
              {run.final_answer}
            </p>
          ) : (
            <p className="text-sm text-muted-foreground">No answer was generated.</p>
          )}

          {synthesis && (synthesis.provider || synthesis.model) && (
            <div className="flex flex-wrap gap-6 border-t border-border pt-3 text-xs text-muted-foreground">
              {synthesis.provider && (
                <span>
                  Generated by: <span className="font-medium text-foreground">{synthesis.provider}</span>
                </span>
              )}
              {synthesis.model && <span>Model: {synthesis.model}</span>}
              <span>
                Fallback used: <span className="font-medium text-foreground">{synthesis.fallback_used ? "Yes" : "No"}</span>
              </span>
            </div>
          )}
        </CardContent>
      </Card>

      <CitationList citations={citations} />
      <EvidencePanel citations={citations} />
    </div>
  );
}
