"""Sprint 16 Phase 7B.13 -- `ExecutionAttempt` persistence tests.

Real database (via the `session` fixture already used throughout this
suite) -- no mocks, no Docker contact anywhere in this file. Proves the
durable row Phase 7B.12's design depends on: `id` survives create ->
commit -> reload, `container_name` and `container_id` round-trip exactly
as opaque strings (never generated, never contacted, never validated
against a real Docker daemon here), and the constraints Phase 7B.12's
recovery protocol needs (`UNIQUE(container_name)`, `UNIQUE(container_id)`
allowing multiple NULLs, `UNIQUE(execution_job_id, attempt_number)`,
`ON DELETE CASCADE` from `ExecutionJob`) actually hold in real Postgres.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator

import pytest
import pytest_asyncio
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from app.database.session import async_session_factory, engine
from app.modules.auth.models import User
from app.modules.execution.enums import ExecutionAttemptStatus, ExecutionJobStatus
from app.modules.execution.models import ExecutionAttempt, ExecutionJob
from app.modules.execution.repository import ExecutionAttemptRepository, ExecutionJobRepository
from app.modules.execution.schemas import ExecutionAttemptCreate, ExecutionAttemptRead, ExecutionJobCreate
from app.modules.projects.models import Project, ProjectStatus, ProjectType
from execution_launcher.models import ExecutionCapability, ExecutionOperation, ResourceClass


# Same narrow, test-local workaround as the other execution_* test files
# for the repository's known module-level-engine + function-scoped-
# event-loop interaction. Does not touch app/database/session.py,
# conftest.py, or pytest.ini.
@pytest_asyncio.fixture(autouse=True)
async def _dispose_engine_pool_between_tests():
    await engine.dispose()
    yield


async def _make_owner_and_project(session, *, name: str) -> Project:
    user = User(
        email=f"pytest-attempt-{uuid.uuid4().hex[:12]}@example.com",
        hashed_password="not-a-real-hash",
        full_name="Attempt Test User",
        is_active=True,
    )
    session.add(user)
    await session.flush()

    project = Project(
        owner_id=user.id,
        name=name,
        description="Created by test_execution_attempt_persistence.py",
        project_type=ProjectType.RESEARCH,
        status=ProjectStatus.ACTIVE,
    )
    session.add(project)
    await session.flush()
    await session.commit()
    return project


@pytest_asyncio.fixture
async def project(session) -> AsyncIterator[Project]:
    proj = await _make_owner_and_project(session, name="Attempt Test Project")
    yield proj
    user = await session.get(User, proj.owner_id)
    if user is not None:
        await session.delete(user)
        await session.commit()


def _matmul_job_create(project: Project) -> ExecutionJobCreate:
    return ExecutionJobCreate(
        project_id=project.id,
        owner_id=project.owner_id,
        experiment_plan_id=uuid.uuid4(),
        experiment_plan_version=1,
        capability=ExecutionCapability.ARRAY_COMPUTE,
        operation=ExecutionOperation.MATMUL,
        resource_class=ResourceClass.CLASS_ARRAY,
        parameters={},
        input_asset_ids=[],
    )


def _job_from_create(payload: ExecutionJobCreate, *, status: ExecutionJobStatus = ExecutionJobStatus.PENDING) -> ExecutionJob:
    data = payload.model_dump()
    data["input_asset_ids"] = [str(asset_id) for asset_id in payload.input_asset_ids]
    return ExecutionJob(status=status, **data)


async def _make_job(session, project: Project) -> ExecutionJob:
    job = await ExecutionJobRepository(session).create(_job_from_create(_matmul_job_create(project)))
    await session.commit()
    return job


def _container_name_for(attempt_id: uuid.UUID) -> str:
    """A synthetic, deterministic string -- the exact shape a future
    service would compute (Phase 7B.12 Part 5), NOT generated by any code
    under test here. Persistence tests only care that whatever string is
    handed in round-trips exactly."""
    return f"aikdap-exec-{attempt_id}"


def _attempt_from_create(payload: ExecutionAttemptCreate) -> ExecutionAttempt:
    return ExecutionAttempt(**payload.model_dump())


# ---------------------------------------------------------------------------
# 1-2. Create and read
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_and_get_by_id_round_trips_all_fields(session, project):
    job = await _make_job(session, project)
    attempt_id = uuid.uuid4()
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(attempt_id)
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    fetched = await ExecutionAttemptRepository(session).get_by_id(attempt.id)

    assert fetched is not None
    assert fetched.id == attempt.id
    assert fetched.execution_job_id == job.id
    assert fetched.attempt_number == 1
    assert fetched.container_name == _container_name_for(attempt_id)
    assert fetched.container_id is None
    assert fetched.status == ExecutionAttemptStatus.PENDING_CREATE
    assert fetched.exit_code is None
    assert fetched.error_message is None
    assert fetched.started_at is None
    assert fetched.completed_at is None


# ---------------------------------------------------------------------------
# 3. Default status
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_new_attempt_defaults_to_pending_create_without_being_set_explicitly(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    assert attempt.status == ExecutionAttemptStatus.PENDING_CREATE


# ---------------------------------------------------------------------------
# 4-5. container_id: NULL before Docker, round-trips once (synthetically) set
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_attempt_can_exist_with_null_container_id(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    fetched = await ExecutionAttemptRepository(session).get_by_id(attempt.id)
    assert fetched.container_id is None


@pytest.mark.asyncio
async def test_container_id_round_trips_as_an_opaque_string(session, project):
    """A synthetic test container ID -- this file never contacts Docker,
    so this proves storage fidelity only, not real Docker identity."""
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt_row = _attempt_from_create(payload)
    attempt_row.container_id = "sha256:test-only-synthetic-container-id-not-real-docker"
    attempt = await ExecutionAttemptRepository(session).create(attempt_row)
    await session.commit()

    fetched = await ExecutionAttemptRepository(session).get_by_id(attempt.id)
    assert fetched.container_id == "sha256:test-only-synthetic-container-id-not-real-docker"


# ---------------------------------------------------------------------------
# 6-7. container_name and attempt_number round-trip
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_container_name_round_trips_exactly(session, project):
    job = await _make_job(session, project)
    attempt_id_for_name = uuid.uuid4()
    expected_name = _container_name_for(attempt_id_for_name)
    payload = ExecutionAttemptCreate(execution_job_id=job.id, attempt_number=1, container_name=expected_name)
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    fetched = await ExecutionAttemptRepository(session).get_by_id(attempt.id)
    assert fetched.container_name == expected_name


@pytest.mark.asyncio
async def test_valid_attempt_numbers_persist(session, project):
    job = await _make_job(session, project)
    for number in (1, 2, 3):
        payload = ExecutionAttemptCreate(
            execution_job_id=job.id, attempt_number=number, container_name=_container_name_for(uuid.uuid4())
        )
        attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
        await session.commit()
        assert attempt.attempt_number == number


# ---------------------------------------------------------------------------
# 8-10. Uniqueness constraints
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_duplicate_container_name_rejected(session, project):
    job = await _make_job(session, project)
    shared_name = _container_name_for(uuid.uuid4())

    payload_a = ExecutionAttemptCreate(execution_job_id=job.id, attempt_number=1, container_name=shared_name)
    await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_a))
    await session.commit()

    # The violating insert runs in its own short-lived session, closed
    # (and its aborted transaction implicitly rolled back) on the way out
    # of the `async with` block regardless of the exception -- keeps the
    # primary `session` fixture's connection/transaction state untouched
    # by the failure, avoiding the known module-level-engine +
    # function-scoped-event-loop pool fragility a mid-test failed-flush-
    # then-continue on the SAME session can trigger.
    payload_b = ExecutionAttemptCreate(execution_job_id=job.id, attempt_number=2, container_name=shared_name)
    async with async_session_factory() as violating_session:
        with pytest.raises(IntegrityError):
            await ExecutionAttemptRepository(violating_session).create(_attempt_from_create(payload_b))

    # The original attempt is unaffected, verified via its own fresh session.
    async with async_session_factory() as verify_session:
        result = await verify_session.execute(
            select(ExecutionAttempt).where(ExecutionAttempt.container_name == shared_name)
        )
        rows = result.scalars().all()
    assert len(rows) == 1
    assert rows[0].attempt_number == 1


@pytest.mark.asyncio
async def test_duplicate_attempt_number_for_same_job_rejected(session, project):
    job = await _make_job(session, project)

    payload_a = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_a))
    await session.commit()

    payload_b = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    async with async_session_factory() as violating_session:
        with pytest.raises(IntegrityError):
            await ExecutionAttemptRepository(violating_session).create(_attempt_from_create(payload_b))


@pytest.mark.asyncio
async def test_same_attempt_number_across_different_jobs_succeeds(session, project):
    job_a = await _make_job(session, project)
    job_b = await _make_job(session, project)

    payload_a = ExecutionAttemptCreate(
        execution_job_id=job_a.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    payload_b = ExecutionAttemptCreate(
        execution_job_id=job_b.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt_a = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_a))
    attempt_b = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_b))
    await session.commit()

    assert attempt_a.attempt_number == 1
    assert attempt_b.attempt_number == 1
    assert attempt_a.execution_job_id != attempt_b.execution_job_id


@pytest.mark.asyncio
async def test_multiple_attempts_with_null_container_id_coexist(session, project):
    """Postgres treats NULLs as distinct under a UNIQUE index -- two
    not-yet-created attempts (container_id still NULL) must coexist."""
    job = await _make_job(session, project)
    payload_a = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    payload_b = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=2, container_name=_container_name_for(uuid.uuid4())
    )
    attempt_a = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_a))
    attempt_b = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload_b))
    await session.commit()

    assert attempt_a.container_id is None
    assert attempt_b.container_id is None


# ---------------------------------------------------------------------------
# 11. Cascade delete
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_deleting_job_cascades_to_execution_attempts(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()
    attempt_id = attempt.id

    user = await session.get(User, project.owner_id)
    await session.delete(user)
    await session.commit()

    # A second, independent session avoids the `expire_on_commit=False`
    # identity-map staleness already root-caused in
    # test_execution_job_persistence.py's cascade test -- a fresh session
    # has no cached pre-delete object to serve stale.
    async with async_session_factory() as verify_session:
        assert await ExecutionAttemptRepository(verify_session).get_by_id(attempt_id) is None


# ---------------------------------------------------------------------------
# 12. Enum round-trip
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_attempt_status_enum_round_trips_as_the_real_enum_member(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    fetched = await ExecutionAttemptRepository(session).get_by_id(attempt.id)
    assert fetched.status is ExecutionAttemptStatus.PENDING_CREATE
    assert isinstance(fetched.status, ExecutionAttemptStatus)


# ---------------------------------------------------------------------------
# 13. Timestamps
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_timestamp_semantics(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    assert attempt.created_at is not None
    assert attempt.updated_at is not None
    # started_at/completed_at are outputs of a future launcher observing
    # the container -- absent until this slice's callers explicitly set
    # them (which none do).
    assert attempt.started_at is None
    assert attempt.completed_at is None


# ---------------------------------------------------------------------------
# 14. Missing attempt
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_get_by_id_returns_none_for_unknown_attempt(session):
    assert await ExecutionAttemptRepository(session).get_by_id(uuid.uuid4()) is None


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_attempt_id_differs_from_job_id_and_is_stable_across_reload(session, project):
    job = await _make_job(session, project)
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(uuid.uuid4())
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()
    original_id = attempt.id

    assert attempt.id != job.id

    async with async_session_factory() as reload_session:
        reloaded = await ExecutionAttemptRepository(reload_session).get_by_id(original_id)
    assert reloaded.id == original_id


@pytest.mark.asyncio
async def test_execution_attempt_read_schema_round_trips_from_orm_row(session, project):
    job = await _make_job(session, project)
    attempt_id = uuid.uuid4()
    payload = ExecutionAttemptCreate(
        execution_job_id=job.id, attempt_number=1, container_name=_container_name_for(attempt_id)
    )
    attempt = await ExecutionAttemptRepository(session).create(_attempt_from_create(payload))
    await session.commit()

    read = ExecutionAttemptRead.model_validate(attempt)
    assert read.id == attempt.id
    assert read.container_name == _container_name_for(attempt_id)
    assert read.status is ExecutionAttemptStatus.PENDING_CREATE


# ---------------------------------------------------------------------------
# Security: the model carries Docker IDENTITY, never Docker POLICY.
# ---------------------------------------------------------------------------


_FORBIDDEN_POLICY_FIELDS = (
    "image",
    "command",
    "entrypoint",
    "network_mode",
    "privileged",
    "cap_add",
    "cap_drop",
    "devices",
    "environment",
    "mounts",
    "socket",
    "secrets",
)


def test_execution_attempt_model_has_no_docker_policy_fields():
    columns = {c.name for c in ExecutionAttempt.__table__.columns}
    for forbidden in _FORBIDDEN_POLICY_FIELDS:
        assert forbidden not in columns, f"ExecutionAttempt must not carry Docker policy field {forbidden!r}"


def test_execution_attempt_model_columns_are_exactly_identity_and_lifecycle():
    expected = {
        "id",
        "execution_job_id",
        "attempt_number",
        "container_name",
        "container_id",
        "status",
        "exit_code",
        "error_message",
        "started_at",
        "completed_at",
        "created_at",
        "updated_at",
    }
    actual = {c.name for c in ExecutionAttempt.__table__.columns}
    assert actual == expected


def _imports_any_of(source: str, module_names: set[str]) -> bool:
    import ast

    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            if any(alias.name.split(".")[0] in module_names for alias in node.names):
                return True
        elif isinstance(node, ast.ImportFrom):
            if (node.module or "").split(".")[0] in module_names:
                return True
    return False


@pytest.mark.parametrize("module", ["enums", "models", "repository", "schemas"])
def test_execution_module_files_never_import_docker_celery_or_subprocess(module):
    import importlib
    import pathlib

    mod = importlib.import_module(f"app.modules.execution.{module}")
    source = pathlib.Path(mod.__file__).read_text(encoding="utf-8")
    assert not _imports_any_of(source, {"docker", "celery", "subprocess"})


def test_docker_sdk_not_imported_at_runtime_by_execution_module():
    """AST-based (Sprint 16 Phase 7B.25 correction): a `sys.modules`
    check is no longer a valid proxy here -- `execution_launcher.
    launcher` now legitimately imports the Docker SDK elsewhere in this
    codebase, and pytest runs the whole suite in one process, so
    `sys.modules["docker"]` can already be populated by an unrelated
    test file by the time this one runs. Re-checks the same three
    modules' own source directly instead."""
    import pathlib

    import app.modules.execution.models as models_module
    import app.modules.execution.repository as repository_module
    import app.modules.execution.schemas as schemas_module

    for module in (models_module, repository_module, schemas_module):
        source = pathlib.Path(module.__file__).read_text(encoding="utf-8")
        assert not _imports_any_of(source, {"docker"}), module.__name__


def test_execution_attempt_repository_has_no_launch_or_lifecycle_methods():
    forbidden_substrings = ("launch", "retry", "reconcile", "cancel", "kill", "start", "stop", "dispatch")
    methods = [name for name in dir(ExecutionAttemptRepository) if not name.startswith("_")]
    for method in methods:
        for forbidden in forbidden_substrings:
            assert forbidden not in method.lower()
