/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report the operational state of the platform and its dependencies.
         *
         *     Always answers HTTP 200, whatever it finds. The status lives in the
         *     body; encoding it in the HTTP status too would mean a liveness
         *     probe restarting a perfectly healthy container because a
         *     third-party model provider ran out of free quota for the day.
         *
         *     Costs nothing meaningful to call: no inference, no reranking, no
         *     model quota. See `HealthService` for what each component check
         *     actually does.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email and password and receive a token pair.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new access/refresh token pair.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the currently authenticated user.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List the current user's projects.
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project owned by the current user.
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Fetch a single project owned by the current user.
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Delete a project owned by the current user.
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Partially update a project owned by the current user.
         */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Asset
         * @description Upload a file as a new asset within one of the current user's projects.
         */
        post: operations["upload_asset_api_v1_assets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Assets
         * @description Search the current user's assets by text, project, type, status, or tags.
         */
        get: operations["search_assets_api_v1_assets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Asset
         * @description Manually (re)queue an owned asset for the extract/chunk pipeline.
         *
         *     Assets are queued automatically on upload; this endpoint is for
         *     retrying a `FAILED` asset or reprocessing after the pipeline
         *     changes.
         */
        post: operations["reprocess_asset_api_v1_assets__asset_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/download/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Asset
         * @description Download the raw file content of an owned asset.
         */
        get: operations["download_asset_api_v1_assets_download__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description List the current user's assets, optionally scoped to one project.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description Fetch a single asset owned by the current user.
         */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Asset
         * @description Delete an asset owned by the current user, including its stored file.
         */
        delete: operations["delete_asset_api_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Asset
         * @description Partially update an asset's metadata (not its underlying file).
         */
        patch: operations["update_asset_api_v1_assets__asset_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List the current user's tasks, optionally filtered. Archived tasks
         *     are excluded unless `include_archived=true` or `status=ARCHIVED` is
         *     explicitly requested.
         */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description Create a new task within a project owned by the current user.
         */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description Fetch a single task owned by the current user (archived or not).
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task
         * @description Archive (soft-delete) a task owned by the current user.
         */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Task
         * @description Partially update a task owned by the current user.
         */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/knowledge-base/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic Search
         * @description Two-stage semantic search over the current user's knowledge chunks.
         *
         *     Stage 1 embeds `query` with the same local BGE-M3 model used to
         *     embed chunks and retrieves `candidate_k` chunks by pgvector cosine
         *     distance. Stage 2 rescores those candidates with the local
         *     BGE-Reranker-v2-m3 cross-encoder and keeps the best `top_k`. Stage
         *     3 then drops anything scoring below `relevance_threshold`, so an
         *     unrelated question returns nothing rather than the least-bad
         *     chunks — `results` is accepted evidence, not merely ranked
         *     evidence.
         *
         *     Optionally scoped to one project and/or one asset the caller owns;
         *     supplying a project/asset the caller does not own is rejected, not
         *     silently filtered to an empty result — and ownership is applied in
         *     stage 1, so the reranker never sees another user's chunks.
         *
         *     If reranking cannot run, stage 1's results are returned in
         *     retrieval order and `reranking_status` says so; scores are never
         *     fabricated and no cloud model is substituted. Synthesis (Sprint 9E)
         *     does not happen here — this returns ranked evidence, not an answer.
         */
        post: operations["semantic_search_api_v1_knowledge_base_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-base/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chunks
         * @description List knowledge chunks in a project owned by the current user,
         *     optionally scoped to one asset.
         */
        get: operations["list_chunks_api_v1_knowledge_base_chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-base/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chunk
         * @description Fetch a single knowledge chunk owned by the current user.
         */
        get: operations["get_chunk_api_v1_knowledge_base_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Research Run
         * @description Start a research run and return immediately with its id and status.
         *
         *     The LangGraph workflow runs in the Celery worker; poll
         *     `GET /research/runs/{run_id}` for the plan, trace, and final answer.
         */
        post: operations["start_research_run_api_v1_research_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Research Runs
         * @description List the current user's research runs, newest first.
         */
        get: operations["list_research_runs_api_v1_research_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Research Run
         * @description Fetch one run with its full execution trace and agent transcript.
         */
        get: operations["get_research_run_api_v1_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Return basic API metadata.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIProfile
         * @description AI-derived metadata for an asset.
         *
         *     `status`/`error` are stored as plain fields inside this existing
         *     JSONB-backed model — no new database column or migration — so a
         *     failed AI step is recorded without ever touching
         *     `Asset.processing_status`/`Asset.processing_error`, which describe
         *     the deterministic extract/chunk pipeline, not this one.
         */
        AIProfile: {
            /** Summary */
            summary?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Entities */
            entities?: string[];
            /** Topics */
            topics?: string[];
            /** Language */
            language?: string | null;
            /** @default pending */
            embedding_status: components["schemas"]["EmbeddingStatus"];
            /** Related Assets */
            related_assets?: string[];
            /** Related Projects */
            related_projects?: string[];
            /** Generated By */
            generated_by?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** @default pending */
            status: components["schemas"]["AIProfileStatus"];
            /** Error */
            error?: string | null;
        };
        /**
         * AIProfileStatus
         * @description Lifecycle of the AI-understanding step for one asset.
         *
         *     Deliberately separate from `AssetProcessingStatus`: extraction and
         *     chunking (the deterministic, primary pipeline) can succeed even
         *     when this stays `FAILED`/`UNAVAILABLE` — raw extracted text must
         *     survive an AI failure, so a failed AI step must never be reported
         *     through the same status field that governs whether the asset's
         *     text was recovered at all.
         * @enum {string}
         */
        AIProfileStatus: "pending" | "completed" | "failed" | "unavailable";
        /**
         * AgentMessageRead
         * @description One agent transcript entry within a run.
         */
        AgentMessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Step Id */
            step_id: string | null;
            /** Sequence */
            sequence: number;
            role: components["schemas"]["AgentMessageRole"];
            /** Agent Name */
            agent_name: string;
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AgentMessageRole
         * @description Who produced a transcript entry.
         *
         *     Mirrors the constitution's workflow roles rather than a chat
         *     protocol's roles: AIKDAP's agents communicate through shared graph
         *     state, not through a conversation.
         * @enum {string}
         */
        AgentMessageRole: "system" | "planner" | "router" | "agent" | "tool" | "aggregator";
        /**
         * AssetProcessingStatus
         * @description State of the extract -> chunk -> (future) embed pipeline for an
         *     asset. Distinct from `AssetStatus`, which tracks lifecycle
         *     (active/archived), not pipeline progress.
         *
         *     `UNSUPPORTED` is a deliberate non-error terminal state: it means no
         *     extractor is implemented yet for the asset's MIME type (a known,
         *     expected gap), as opposed to `FAILED`, which means something broke
         *     while processing a MIME type we do support.
         * @enum {string}
         */
        AssetProcessingStatus: "pending" | "queued" | "extracting" | "chunking" | "embedding" | "completed" | "failed" | "unsupported";
        /**
         * AssetRead
         * @description Public representation of an asset.
         *
         *     `storage_path` is intentionally omitted — clients retrieve file
         *     bytes via `GET /assets/download/{id}`, never a raw filesystem or
         *     bucket path.
         */
        AssetRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            asset_type: components["schemas"]["AssetType"];
            status: components["schemas"]["AssetStatus"];
            /** Mime Type */
            mime_type: string;
            /** File Name */
            file_name: string;
            /** File Extension */
            file_extension: string;
            /** File Size */
            file_size: number;
            /** Checksum */
            checksum: string;
            source: components["schemas"]["AssetSource"];
            /** Version */
            version: number;
            /** Tags */
            tags: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            ai_profile: components["schemas"]["AIProfile"];
            /** Created By */
            created_by: string | null;
            processing_status: components["schemas"]["AssetProcessingStatus"];
            /** Processing Error */
            processing_error: string | null;
            /** Processing Started At */
            processing_started_at: string | null;
            /** Processing Completed At */
            processing_completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AssetSource
         * @description How an asset came to exist in the platform.
         * @enum {string}
         */
        AssetSource: "upload" | "generated" | "imported";
        /**
         * AssetStatus
         * @description Lifecycle state of an asset.
         * @enum {string}
         */
        AssetStatus: "active" | "archived";
        /**
         * AssetType
         * @description The kind of content an asset represents.
         * @enum {string}
         */
        AssetType: "document" | "dataset" | "report" | "summary" | "chart" | "presentation" | "image" | "note" | "workflow_output" | "other";
        /**
         * AssetUpdate
         * @description Payload for partially updating an asset's metadata (not its file).
         *
         *     Unset fields are left untouched; explicit `null` clears a field.
         */
        AssetUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["AssetStatus"] | null;
            /** Tags */
            tags?: string[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_upload_asset_api_v1_assets_upload_post */
        Body_upload_asset_api_v1_assets_upload_post: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            asset_type?: components["schemas"]["AssetType"] | null;
            /** Tags */
            tags?: string | null;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * ComponentHealth
         * @description One dependency's state, plus whatever context helps diagnose it.
         */
        ComponentHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * ComponentStatus
         * @description How one dependency is doing.
         *
         *     The set is a superset of what any single component uses — LLM
         *     providers can be `quota_exhausted`, a database cannot — because one
         *     vocabulary across the whole response is easier to read and to alert
         *     on than a different enum per component.
         * @enum {string}
         */
        ComponentStatus: "healthy" | "degraded" | "configured" | "quota_exhausted" | "rate_limited" | "unavailable" | "loading" | "disabled" | "not_configured" | "configuration_error" | "unknown";
        /**
         * EmbeddingProviderName
         * @description Identifies which embedding backend produced (or will produce) a
         *     chunk's vector. `NONE` is the only provider active this sprint —
         *     the others are named here so the schema and API are ready for
         *     each backend without further changes once implemented.
         * @enum {string}
         */
        EmbeddingProviderName: "none" | "openai" | "nvidia_nim" | "voyage_ai" | "jina_ai" | "local";
        /**
         * EmbeddingStatus
         * @description Status of the (future) embedding-generation pipeline for an asset
         *     or knowledge chunk. Reused by `app.modules.knowledge_base` rather
         *     than duplicated, since it's the same underlying concept.
         * @enum {string}
         */
        EmbeddingStatus: "pending" | "processing" | "completed" | "failed" | "not_applicable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description The full health report.
         *
         *     Always served with HTTP 200, including when `status` is
         *     `unhealthy`. The endpoint's job is to *report* the state; using the
         *     HTTP status to encode it as well means an orchestrator's liveness
         *     probe would restart a container whose only problem is that a
         *     third-party model provider ran out of free quota.
         */
        HealthResponse: {
            status: components["schemas"]["OverallStatus"];
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ComponentHealth"];
            };
        };
        /**
         * KnowledgeChunkRead
         * @description Public representation of a knowledge chunk.
         *
         *     `embedding` is intentionally omitted — it's a 1024-float vector,
         *     not useful to typical API consumers browsing the knowledge base,
         *     and never returned outside `app.modules.knowledge_base.search`
         *     (which surfaces a similarity score, not the raw vector).
         */
        KnowledgeChunkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Token Count */
            token_count: number | null;
            embedding_status: components["schemas"]["EmbeddingStatus"];
            embedding_provider: components["schemas"]["EmbeddingProviderName"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LoginRequest
         * @description Payload for authenticating with email and password.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OverallStatus
         * @description Whether the platform as a whole can serve.
         *
         *     `unhealthy` is reserved for losing something the API cannot work
         *     without at all. Everything else is `degraded`: an unconfigured
         *     optional fallback, a dead reranker, or a spent Gemini quota all
         *     reduce capability without stopping the platform, and reporting them
         *     as `unhealthy` would train operators to ignore the field.
         * @enum {string}
         */
        OverallStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * ProjectCreate
         * @description Payload for creating a new project.
         */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** @default research */
            project_type: components["schemas"]["ProjectType"];
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /**
         * ProjectRead
         * @description Public representation of a project.
         */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            project_type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            /** Color */
            color: string | null;
            /** Icon */
            icon: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @description Lifecycle state of a project.
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /**
         * ProjectType
         * @description The kind of work a project is oriented around.
         * @enum {string}
         */
        ProjectType: "research" | "business" | "hybrid";
        /**
         * ProjectUpdate
         * @description Payload for partially updating a project. Unset fields are left untouched.
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            project_type?: components["schemas"]["ProjectType"] | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /**
         * RefreshTokenRequest
         * @description Payload for exchanging a refresh token for a new token pair.
         */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ResearchGroundingStatus
         * @description How well the final answer is supported by retrieved evidence.
         *
         *     Distinct from `ResearchRunStatus`: a run can complete successfully
         *     and still be honestly unable to answer. The two questions "did the
         *     workflow execute" and "is the answer supported" have different
         *     answers and must not be collapsed into one field.
         *
         *     Assigned by the backend from the validated citation set, never
         *     copied from what the model claimed about itself — a model asserting
         *     it was grounded is not evidence that it was.
         * @enum {string}
         */
        ResearchGroundingStatus: "grounded" | "partially_grounded" | "insufficient_evidence" | "failed";
        /**
         * ResearchRunAccepted
         * @description Immediate `201` response: the run exists, execution has been queued.
         *
         *     Deliberately small. The workflow has not started when this is
         *     returned, so anything it produces would be a lie at this point —
         *     poll `GET /research/runs/{run_id}` for results.
         */
        ResearchRunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["ResearchRunStatus"];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Query */
            query: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ResearchRunCreate
         * @description Payload for starting a research run.
         */
        ResearchRunCreate: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Query */
            query: string;
            /** Task Id */
            task_id?: string | null;
            /**
             * Include Assets
             * @description Search the project's own knowledge base.
             * @default true
             */
            include_assets: boolean;
            /**
             * Include Web
             * @description Gather external references (simulated in this release).
             * @default true
             */
            include_web: boolean;
            /**
             * Max Results
             * @default 5
             */
            max_results: number;
        };
        /**
         * ResearchRunDetail
         * @description A run together with its full Explainable-AI trace.
         */
        ResearchRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Task Id */
            task_id: string | null;
            /** Query */
            query: string;
            status: components["schemas"]["ResearchRunStatus"];
            /** Include Assets */
            include_assets: boolean;
            /** Include Web */
            include_web: boolean;
            /** Max Results */
            max_results: number;
            /** Objective */
            objective: string | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            } | null;
            /** Final Answer */
            final_answer: string | null;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[] | null;
            grounding_status: components["schemas"]["ResearchGroundingStatus"] | null;
            /** Error Message */
            error_message: string | null;
            /** Celery Task Id */
            celery_task_id: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Steps */
            steps?: components["schemas"]["ResearchStepRead"][];
            /** Messages */
            messages?: components["schemas"]["AgentMessageRead"][];
        };
        /**
         * ResearchRunRead
         * @description Full state of a research run.
         */
        ResearchRunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Task Id */
            task_id: string | null;
            /** Query */
            query: string;
            status: components["schemas"]["ResearchRunStatus"];
            /** Include Assets */
            include_assets: boolean;
            /** Include Web */
            include_web: boolean;
            /** Max Results */
            max_results: number;
            /** Objective */
            objective: string | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            } | null;
            /** Final Answer */
            final_answer: string | null;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[] | null;
            grounding_status: components["schemas"]["ResearchGroundingStatus"] | null;
            /** Error Message */
            error_message: string | null;
            /** Celery Task Id */
            celery_task_id: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ResearchRunStatus
         * @description Lifecycle state of one research run.
         *
         *     `PENDING` is the state a run is in between `POST /research/run`
         *     returning `201` and the Celery worker picking it up — the API
         *     always returns immediately, so callers observe this state.
         * @enum {string}
         */
        ResearchRunStatus: "pending" | "running" | "completed" | "failed" | "cancelled";
        /**
         * ResearchStepRead
         * @description One node's execution record within a run.
         */
        ResearchStepRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Step Index */
            step_index: number;
            /** Node Name */
            node_name: string;
            /** Title */
            title: string;
            status: components["schemas"]["ResearchStepStatus"];
            /** Summary */
            summary: string | null;
            /** Output Payload */
            output_payload: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ResearchStepStatus
         * @description Execution state of a single graph node within a run.
         *
         *     `SKIPPED` records a node that the plan named but the router did not
         *     dispatch to — the trace should show what was *considered*, not only
         *     what ran.
         * @enum {string}
         */
        ResearchStepStatus: "pending" | "running" | "completed" | "failed" | "skipped";
        /**
         * SemanticSearchRequest
         * @description Request body for `POST /knowledge-base/search`.
         *
         *     `candidate_k` is stage 1's pool size and `top_k` the final result
         *     count; `candidate_k` should exceed `top_k` so the stage-2 reranker
         *     has something to reorder. Both default to `None` here rather than
         *     to literals, so the configured `RERANKER_CANDIDATE_K`/
         *     `RERANKER_TOP_K` remain the single source of truth.
         */
        SemanticSearchRequest: {
            /** Query */
            query: string;
            /** Top K */
            top_k?: number | null;
            /** Candidate K */
            candidate_k?: number | null;
            /** Project Id */
            project_id?: string | null;
            /** Asset Id */
            asset_id?: string | null;
            /**
             * Rerank
             * @default true
             */
            rerank: boolean;
        };
        /**
         * SemanticSearchResponse
         * @description Response body for `POST /knowledge-base/search`.
         */
        SemanticSearchResponse: {
            /** Query */
            query: string;
            /** Model */
            model: string;
            /** Reranker Model */
            reranker_model?: string | null;
            /** Reranking Status */
            reranking_status: string;
            /** Reranking Error */
            reranking_error?: string | null;
            /** Candidate Count */
            candidate_count: number;
            /**
             * Reranked Count
             * @default 0
             */
            reranked_count: number;
            /**
             * Rejected Count
             * @default 0
             */
            rejected_count: number;
            /** Relevance Threshold */
            relevance_threshold?: number | null;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["SemanticSearchResult"][];
        };
        /**
         * SemanticSearchResult
         * @description One ranked chunk from a semantic search.
         *
         *     Carries both stage scores. They are different measurements on
         *     different scales and neither is derived from the other.
         */
        SemanticSearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Content */
            content: string;
            /** Chunk Index */
            chunk_index: number;
            /** Rank */
            rank: number;
            /** Retrieval Rank */
            retrieval_rank: number;
            /** Distance */
            distance: number;
            /** Similarity */
            similarity: number;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /**
         * TaskCreate
         * @description Payload for creating a new task within a project.
         */
        TaskCreate: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Input Prompt */
            input_prompt: string;
            task_type: components["schemas"]["TaskType"];
            /** @default MEDIUM */
            priority: components["schemas"]["TaskPriority"];
        };
        /**
         * TaskPriority
         * @description Execution priority of a task.
         * @enum {string}
         */
        TaskPriority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /**
         * TaskRead
         * @description Public representation of a task.
         */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Input Prompt */
            input_prompt: string;
            task_type: components["schemas"]["TaskType"];
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /** Planner Output */
            planner_output: {
                [key: string]: unknown;
            } | null;
            /** Estimated Cost */
            estimated_cost: string | null;
            /** Estimated Tokens */
            estimated_tokens: number | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @description Lifecycle state of a task.
         *
         *     `ARCHIVED` is the soft-delete state: `DELETE /tasks/{id}` sets a
         *     task to this status rather than removing its row.
         * @enum {string}
         */
        TaskStatus: "DRAFT" | "QUEUED" | "PLANNING" | "RUNNING" | "WAITING" | "COMPLETED" | "FAILED" | "CANCELLED" | "ARCHIVED";
        /**
         * TaskType
         * @description The category of work a task represents.
         * @enum {string}
         */
        TaskType: "RESEARCH" | "BUSINESS_ANALYSIS" | "FINANCIAL_ANALYSIS" | "DATA_ANALYSIS" | "REPORT_GENERATION" | "CUSTOM";
        /**
         * TaskUpdate
         * @description Payload for partially updating a task. Unset fields are left untouched.
         */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Input Prompt */
            input_prompt?: string | null;
            task_type?: components["schemas"]["TaskType"] | null;
            status?: components["schemas"]["TaskStatus"] | null;
            priority?: components["schemas"]["TaskPriority"] | null;
        };
        /**
         * TokenPair
         * @description An access/refresh JWT pair returned on login or token refresh.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserCreate
         * @description Payload for registering a new user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * UserRead
         * @description Public representation of a user.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_v1_assets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_assets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_assets_api_v1_assets_search_get: {
        parameters: {
            query?: {
                q?: string | null;
                project_id?: string | null;
                asset_type?: components["schemas"]["AssetType"] | null;
                status?: components["schemas"]["AssetStatus"] | null;
                tags?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_asset_api_v1_assets__asset_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_asset_api_v1_assets_download__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_v1_assets__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: components["schemas"]["TaskStatus"] | null;
                task_type?: components["schemas"]["TaskType"] | null;
                priority?: components["schemas"]["TaskPriority"] | null;
                include_archived?: boolean;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_search_api_v1_knowledge_base_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_v1_knowledge_base_chunks_get: {
        parameters: {
            query: {
                project_id: string;
                asset_id?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chunk_api_v1_knowledge_base_chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeChunkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_research_run_api_v1_research_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_runs_api_v1_research_runs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: components["schemas"]["ResearchRunStatus"] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_run_api_v1_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
