/** `ResearchStepRead.output_payload` is `Record<string, unknown> | null`
 * in the generated types — same reason as `Citation`: JSONB with no
 * strict per-node Pydantic schema. This is the synthesis step's
 * payload shape as observed live (provider/model/fallback metadata),
 * used only to render "Generated by" / "Fallback used" when the
 * backend actually supplied them — every field optional, nothing
 * assumed present. */
export interface SynthesisOutput {
  model?: string | null;
  provider?: string | null;
  fallback_used?: boolean;
  primary_model?: string | null;
  primary_error_type?: string | null;
  grounding_status?: string | null;
  citation_count?: number;
  evidence_supplied?: number;
}

export function asSynthesisOutput(
  raw: Record<string, unknown> | null | undefined,
): SynthesisOutput | null {
  return raw ? (raw as SynthesisOutput) : null;
}
