"""create_execution_attempts_table

Revision ID: 3abf531e2215
Revises: 452c53f7a4fe
Create Date: 2026-09-03 18:21:19.861149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abf531e2215'
down_revision: Union[str, None] = '452c53f7a4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_attempts',
    sa.Column('execution_job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING_CREATE', 'CREATED', 'RUNNING', 'EXITED', 'UNKNOWN', name='execution_attempt_status_enum'), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], name=op.f('fk_execution_attempts_execution_job_id_execution_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_attempts')),
    sa.UniqueConstraint('execution_job_id', 'attempt_number', name='uq_execution_attempts_job_attempt_number')
    )
    op.create_index(op.f('ix_execution_attempts_container_id'), 'execution_attempts', ['container_id'], unique=True)
    op.create_index(op.f('ix_execution_attempts_container_name'), 'execution_attempts', ['container_name'], unique=True)
    op.create_index(op.f('ix_execution_attempts_execution_job_id'), 'execution_attempts', ['execution_job_id'], unique=False)
    op.create_index(op.f('ix_execution_attempts_status'), 'execution_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_attempts_status'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_execution_job_id'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_container_name'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_container_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    # ### end Alembic commands ###

    # Autogenerate does not emit this: `op.drop_table` removes the table
    # but leaves the native Postgres ENUM type behind, so a later
    # `upgrade` re-running `CREATE TYPE` fails with "already exists"
    # (the exact bug found and fixed in `8f4f66de07a7`'s downgrade --
    # applied here proactively rather than rediscovered).
    sa.Enum(name='execution_attempt_status_enum').drop(op.get_bind(), checkfirst=True)
