"""create_execution_jobs_table

Revision ID: 8f4f66de07a7
Revises: fae4f91a412b
Create Date: 2026-09-03 17:23:32.688860+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f4f66de07a7'
down_revision: Union[str, None] = 'fae4f91a412b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('experiment_plan_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_plan_version', sa.Integer(), nullable=False),
    sa.Column('capability', sa.Enum('evaluate_expression', 'array_compute', 'table_compute', name='execution_capability_enum'), nullable=False),
    sa.Column('operation', sa.Enum('evaluate_expression', 'matmul', 'percentile', 'mean', 'std', 'corrcoef', 'groupby_agg', 'pivot_table', name='execution_operation_enum'), nullable=False),
    sa.Column('resource_class', sa.Enum('class_expr', 'class_array', 'class_table', name='resource_class_enum'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LAUNCHED', 'SECURITY_BLOCKED', 'FAILED', 'COMPLETED', name='execution_job_status_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_execution_jobs_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_execution_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_jobs'))
    )
    op.create_index(op.f('ix_execution_jobs_experiment_plan_id'), 'execution_jobs', ['experiment_plan_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_owner_id'), 'execution_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_project_id'), 'execution_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_jobs_project_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_owner_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_experiment_plan_id'), table_name='execution_jobs')
    op.drop_table('execution_jobs')
    # ### end Alembic commands ###

    # Autogenerate does not emit these: `op.drop_table` removes the table
    # but leaves each native Postgres ENUM type behind, so a later
    # `upgrade` re-running `CREATE TYPE` fails with "already exists"
    # (verified by an actual downgrade/upgrade round-trip while authoring
    # this migration). Dropped explicitly, in the reverse of creation order.
    sa.Enum(name='execution_job_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='resource_class_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='execution_operation_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='execution_capability_enum').drop(op.get_bind(), checkfirst=True)
