"""add_asset_processing_and_knowledge_chunks

Revision ID: 92fc3fa98bed
Revises: b5115bfc3a9b
Create Date: 2026-08-06 10:39:28.078222+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92fc3fa98bed'
down_revision: Union[str, None] = 'b5115bfc3a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'not_applicable', name='kb_embedding_status_enum'), nullable=False),
    sa.Column('embedding_provider', sa.Enum('none', 'openai', 'nvidia_nim', 'voyage_ai', 'jina_ai', 'local', name='kb_embedding_provider_enum'), nullable=True),
    sa.Column('embedding_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_knowledge_chunks_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_knowledge_chunks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index(op.f('ix_knowledge_chunks_asset_id'), 'knowledge_chunks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_project_id'), 'knowledge_chunks', ['project_id'], unique=False)

    # `op.add_column` on an *existing* table, unlike `op.create_table`,
    # does not auto-create a native enum type it references — it must
    # be created explicitly first, or the ALTER TABLE fails with
    # "type ... does not exist". `create_type=False` on the column
    # itself then prevents a second, redundant CREATE TYPE attempt.
    processing_status_enum = postgresql.ENUM(
        'pending', 'queued', 'extracting', 'chunking', 'embedding', 'completed', 'failed', 'unsupported',
        name='asset_processing_status_enum',
    )
    processing_status_enum.create(op.get_bind(), checkfirst=True)

    # `nullable=False` with no default would fail on a non-empty `assets`
    # table (Postgres can't backfill a NOT NULL column with nothing to
    # put in it). `server_default` backfills existing rows at add-column
    # time; it's dropped immediately after so the column's only source
    # of truth going forward is the ORM-side default in models.py, not a
    # server default the model doesn't declare.
    op.add_column(
        'assets',
        sa.Column(
            'processing_status',
            postgresql.ENUM(
                'pending', 'queued', 'extracting', 'chunking', 'embedding', 'completed', 'failed', 'unsupported',
                name='asset_processing_status_enum',
                create_type=False,
            ),
            nullable=False,
            server_default='pending',
        ),
    )
    op.alter_column('assets', 'processing_status', server_default=None)
    op.add_column('assets', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'processing_completed_at')
    op.drop_column('assets', 'processing_started_at')
    op.drop_column('assets', 'processing_error')
    op.drop_column('assets', 'processing_status')
    postgresql.ENUM(name='asset_processing_status_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_knowledge_chunks_project_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_asset_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
