"""create research runs steps and agent messages tables

Sprint 7: the research workspace and its Explainable-AI trace.

`op.create_table` creates the three native enum types implicitly, so
(unlike an `add_column` against an existing table) no explicit
`postgresql.ENUM(...).create()` is needed on the way up. Alembic does
not emit the matching drops on the way down, though, so `downgrade`
removes them by hand — without that, a downgrade followed by an upgrade
fails with "type already exists".

Revision ID: f3d098d397cc
Revises: 92fc3fa98bed
Create Date: 2026-08-07 07:16:06.105185+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3d098d397cc'
down_revision: Union[str, None] = '92fc3fa98bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='research_run_status_enum'), nullable=False),
    sa.Column('include_assets', sa.Boolean(), nullable=False),
    sa.Column('include_web', sa.Boolean(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_research_runs_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_research_runs_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index(op.f('ix_research_runs_owner_id'), 'research_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_research_runs_project_id'), 'research_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_task_id'), 'research_runs', ['task_id'], unique=False)
    op.create_table('research_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='research_step_status_enum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_steps_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_steps'))
    )
    op.create_index(op.f('ix_research_steps_run_id'), 'research_steps', ['run_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('system', 'planner', 'router', 'agent', 'tool', 'aggregator', name='agent_message_role_enum'), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_agent_messages_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['research_steps.id'], name=op.f('fk_agent_messages_step_id_research_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_run_id'), 'agent_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_step_id'), 'agent_messages', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_messages_step_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_run_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_research_steps_run_id'), table_name='research_steps')
    op.drop_table('research_steps')
    op.drop_index(op.f('ix_research_runs_task_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_project_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_owner_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###

    # Not emitted by autogenerate: dropping a table does not drop the
    # enum types it referenced.
    bind = op.get_bind()
    for enum_name in (
        'agent_message_role_enum',
        'research_step_status_enum',
        'research_run_status_enum',
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
