import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/common/StatusBadge";
import type { components } from "@/types/api";

type AIProfile = components["schemas"]["AIProfile"];

/** Renders exactly the fields `AIProfile` returns — nothing invented
 * while processing is still in flight (Phase 14/16: "Do not fabricate
 * metadata while processing"). A field that's `null`/empty shows as
 * "Not yet available" rather than being silently omitted, so it's
 * clear the absence is real backend state, not a rendering bug. */
export function AiProfilePanel({ profile }: { profile: AIProfile }) {
  const hasContent = profile.status === "completed";

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-base">AI Understanding</CardTitle>
          <StatusBadge domain="aiProfile" value={profile.status} />
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {profile.status === "failed" && profile.error && (
          <p className="text-sm text-destructive">{profile.error}</p>
        )}
        {profile.status === "unavailable" && (
          <p className="text-sm text-muted-foreground">
            The document-understanding model could not be reached.
            {profile.error ? ` ${profile.error}` : ""}
          </p>
        )}
        {profile.status === "pending" && (
          <p className="text-sm text-muted-foreground">
            AI understanding has not run for this document yet.
          </p>
        )}

        {hasContent && (
          <>
            <Field label="Summary">
              <p className="text-sm text-foreground">
                {profile.summary || "Not provided"}
              </p>
            </Field>

            <Field label="Keywords">
              {profile.keywords && profile.keywords.length > 0 ? (
                <div className="flex flex-wrap gap-1.5">
                  {profile.keywords.map((keyword) => (
                    <Badge key={keyword} variant="secondary">
                      {keyword}
                    </Badge>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">Not provided</p>
              )}
            </Field>

            <Field label="Entities">
              <p className="text-sm text-foreground">
                {profile.entities && profile.entities.length > 0
                  ? profile.entities.join(", ")
                  : "Not provided"}
              </p>
            </Field>

            <Field label="Topics">
              <p className="text-sm text-foreground">
                {profile.topics && profile.topics.length > 0
                  ? profile.topics.join(" · ")
                  : "Not provided"}
              </p>
            </Field>

            <div className="grid grid-cols-2 gap-4 border-t border-border pt-4 text-sm">
              <Field label="Language">
                <p>{profile.language ?? "Not provided"}</p>
              </Field>
              <Field label="Generated by">
                <p>{profile.generated_by ?? "Not provided"}</p>
              </Field>
              {profile.confidence !== null && profile.confidence !== undefined && (
                <Field label="Confidence">
                  <p>{(profile.confidence * 100).toFixed(0)}%</p>
                </Field>
              )}
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-1">
      <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </p>
      {children}
    </div>
  );
}
